[package]
name = "cazan-cli"
description = "The Command Line Tool to install to build your Cazan project"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cazan"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
